server:
 port: 9002
spring:
 application:
  name: CONTACT-SERVICE

eureka:
 client:
  register-with-eureka: true
  fetch-registry: true
  serviceUrl:
   defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
 instance:
  hostname: localhost
  