server:
 port: 8999
 
eureka:
 client:
  register-with-eureka: true
  fetch-registry: true
  serviceUrl:
   defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  healthcheck:
      enabled: true
 instance:
  hostname: localhost

management:
 endpoints:
  web:
   exposure:
    include: "*"
 security:
  enabled: false

spring:
 boot:
  admin:
   client:
    url: http://localhost:8761/admin
    name: CONFIG-SERVER